"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$git_state\
$git_commit\
$git_metrics\
$nodejs\
$bun\
$golang\
$python\
$ruby\
$rust\
$scala\
$solidity\
$terraform\
$zig\
$docker\
$docker_context\
$aws\
$gcloud\
$line_break\
$character"""

[directory]
truncate_to_repo=false
truncation_length = 0

[docker_context]
symbol = "ó°¡¨ "

[git_branch]
symbol = "îœ¥ "
style = "bold red"
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[git_commit]
tag_symbol = ' ï’ '

[git_status]
format = '([${all_status}${ahead_behind}]($style))'
ahead = 'â‡¡${count} '
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count} '
behind = 'â‡£${count} '
conflicted = '~${count} '
untracked = '?${count} '
modified = '!${count} '
deleted = '-${count} '
staged = '+${count} '
stashed = 'ğŸ“¦${count} '


[golang]
symbol = 'î˜§ '
